# Generated by Django 4.1.5 on 2023-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="verify",
            new_name="email_verify",
        ),
        migrations.AlterField(
            model_name="myuser",
            name="verification_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
